on: [push]

name: CI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc-version: ['7.10','8.6.5', '8.8.4','9.6.1']
        cabal-version: ['2.4.1.0', 'latest']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          # GHC 8.8+ only works with cabal v3+
          - ghc-version: 8.8.4
            cabal-version: 2.4.1.0
          - ghc-version: 9.6.1
            cabal-version: 2.4.1.0
    name: Build package for ${{ matrix.ghc-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc-version }}
          cabal-version: ${{ matrix.cabal-version }}
      - name: Build code
        run: |
          ./configure
          make
